version: '3'

services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - true-network
    depends_on:
      - redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    networks:
      - true-network
    volumes:
      - redis-data:/data

networks:
  true-network:

volumes:
  redis-data:
